<a href="https://colab.research.google.com/github/OrlandoMR/TutorialR/blob/master/Tutorial_en_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Tutorial de R</h1>


<h2>Integrantes:</h2>
Orlando Alberto Moncada Rodriguez - 2170133 <br/>
Juan Felipe Ortiz Trillos - 2170105<br/>
Andres Felipe Uribe Garcia - 2160793<br/><br/><br/>

<h2>Historia de R</h2>


R tiene sus orígenes en S, un lenguaje de programación creado en los Laboratorios Bell de Estados Unidos. Sí, los mismos laboratorios que inventaron el transistor, el láser, el sistema operativo Unix y algunas otras cosas más.<br></br>
R es un lenguaje relativamente joven pero que ha experimentado un crecimiento acelerado en su adopción durante los últimos 10 años. <br></br>
En septiembre de 2017, de acuerdo al TIOBE programming community index (2017), que es uno de los índices de más prestigio en el mundo en relación popularidad en el uso de lenguajes de programación, R era el lenguaje número 11 en popularidad, después de haber sido el lenguaje número 18 en el 2016. Esto es sobresaliente si consideramos que R es un lenguaje dedicado únicamente a la estadística, mientras que lenguajes como Python (número 5 en 2017) o Java (número 1) son lenguajes que pueden ser usados para todo tipo de tareas, desde crear sitios web hasta programar robots. <br></br>


---

<h2>Estructuras de control</h2>

Como su nombre lo indica, las estructuras de control nos permiten controlar la manera en que se ejecuta nuestro código.

Las estructuras de control establecen condicionales en nuestros código. Por ejemplo, qué condiciones deben cumplirse para realizar una operación o qué debe ocurrir para ejecutar una función.

Esto es de gran utilidad para determinar la lógica y el orden en que ocurren las operaciones, en especial al definir funciones.

Las estructuras de control más usadas en R son las siguientes:


*   <h2>if, else</h2>

El modelo para un if es

```
if(Condición) {
  operaciones_si_la_condición_es_TRUE
}
```

Si la condición se cumple, es decir, es verdadera (TRUE), entonces se realizan las operaciones. En caso contrario, no ocurre nada y el código con las operaciones no es ejecutado. Se pueden quitar los corchetes e igualmente ejecuta el *if*

Por ejemplo, le pedimos a R que nos muestre el texto “Verdadero” si la condición se cumple

In [ ]:

if( 4 > 3)
    "Verdadero"

[1] "Verdadero"

***else*** complementa un ***if***, pues indica qué ocurrirá cuando la condición no se cumple, es falsa (FALSE), en lugar de no hacer nada.

In [ ]:
# No se cumple la condición y se muestra "Falso"
if(4 > 5) 
{
  "Verdadero"
} else {
    "Falso"
  }

[1] "Falso"

La función ***ifelse( )*** nos permite vectorizar if, else. En lugar de escribir una línea de código para cada comparación, podemos usar una sola llamada a esta función, que se aplicará a todos los elementos de un vector.</br>

Por ejemplo, pedimos sólo los números que son exactamente divisibles entre 2 y 3.

In [ ]:
num <- 1:20

ifelse(num %% 2 == 0 & num %% 3 == 0, "Divisible", "No divisible")

</br> 

*   <h2>for</h2>

La estructura for nos permite ejecutar un bucle (loop), realizando una operación para cada elemento de un conjunto de datos.

Su estructura es la siguiente:

```
for(elemento in objeto) {
  operacion_con_elemento
}
```

usar **print()** sólo mostrará los resultados de las operaciones en la consola, no los asignará a un objeto.

Si deseamos asignar los resultados de un bucle **for** a un objeto, usamos índices.

Aprovechamos que el primer elemento en un bucle siempre es identificado con el número 1 y que continuará realizando operaciones hasta llegar al total de elementos que hemos especificado.

In [1]:
for(numero in 1:10) {
  print(numero)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


</br> 

*   <h2>while</h2>

Este es un tipo de bucle que ocurre mientras una condición es verdadera (TRUE). La operación se realiza hasta que se se llega a cumplir un criterio previamente establecido.

El modelo de while es:



```
while(condicion) {
  operaciones
}
```


In [15]:
conteo <-  0
valor <- 0

while(valor < 50) {
  valor <- valor + sample(x = 1:10, size = 1)
  conteo <- conteo + 1
  print(c("valor: ", valor))
}
print(c("Conteo: ", conteo))

[1] "valor: " "2"      
[1] "valor: " "12"     
[1] "valor: " "19"     
[1] "valor: " "26"     
[1] "valor: " "35"     
[1] "valor: " "43"     
[1] "valor: " "49"     
[1] "valor: " "51"     
[1] "Conteo: " "8"       


<h1> Matrices</h1>

Las matrices y arrays pueden ser descritas como vectores multidimensionales. Al igual que un vector, únicamente pueden contener datos de un sólo tipo, pero además de largo, tienen más dimensiones.

Para crear una matriz requerimos la funcion ` matrix() ` la cual inicializa una matriz con un rango de datos.

Por ejemplo:









In [ ]:
a<-matrix(1:10)
print(a)

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10


Como podemos ver, es tan solo una matriz de una columna pero de 10 filas ya que debe contener valores del 1 al 10.

Para cambiar la cantidad de columnas y filas agregamos 2 parametros a la funcion `matrix()` los cuales son: nrow y ncol que por logica especifican la cantidad de filas y columnas que tendra la matriz, se definen como:  `matrix(argument,nrow = int, ncol = int)` donde int es cualquier numero entero y argument es el rango de datos.

In [ ]:
a<-matrix(1:20, nrow=5,ncol=4)
print(a)

     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20


Se puede observar que el orden de los datos es de arriba hacia abajo y de izquierda hacia derecha con prioridad vertical.

Tambien podemos usar otras 2 funciones llamadas `cbind()` y `rbind()` las cuales unen varios vectores en una sola matriz, se diferencian en la forma de unirse, el primero, organiza los vectores como columna y el segundo como filas.

In [ ]:
#Definimos los vectores
vector1<-1:4
vector2<-5:8
vector3<-9:12

In [ ]:
a<-cbind(vector1,vector2,vector3)
print(a)

     vector1 vector2 vector3
[1,]       1       5       9
[2,]       2       6      10
[3,]       3       7      11
[4,]       4       8      12


In [ ]:
b<-rbind(vector1,vector2,vector3)
print(b)

        [,1] [,2] [,3] [,4]
vector1    1    2    3    4
vector2    5    6    7    8
vector3    9   10   11   12


Ademas existen diversas operaciones aplicables como la multiplicacion por un escalar o la transpuesta de una matriz.

Primero veremos como multiplicar por un escalar para ello usaremos la matriz asignada a la variable b.

A continuacion un ejemplo.

In [ ]:
bEs<-b*2
print(bEs)

        [,1] [,2] [,3] [,4]
vector1    2    4    6    8
vector2   10   12   14   16
vector3   18   20   22   24


Para transponer una matriz necesitaremos la función `t()`:

In [ ]:
tras<-t(bEs)
print(tras)

     vector1 vector2 vector3
[1,]       2      10      18
[2,]       4      12      20
[3,]       6      14      22
[4,]       8      16      24


<h1>Objetos</h1>

En R existen varios tipos de objectos que permiten que el usuario pueda almacenar la información para realizar procedimientos estadísticos y gráficos. Los principales objetos en R son vectores, matrices, arreglos, marcos de datos y listas

<h3>Vectores</h3>

Los vectores entran en la definicion de objeto de R ya que es una estructura en la cual se pueden guardar datos y hacer operaciones con estos.

In [ ]:
edad<-c(20,22,24,12,NA,17)
print(edad)
mayor<-c(TRUE,FALSE,FALSE,TRUE,NA,TRUE)
print(mayor)

[1] 20 22 24 12 NA 17
[1]  TRUE FALSE FALSE  TRUE    NA  TRUE


<h3>Matrices</h3>

Las matrices al igual que los vectores son objetos 2-dimensionales para recolectar datos

In [ ]:
ma<-cbind(edad,mayor)
print(ma)

     edad mayor
[1,]   20     1
[2,]   22     0
[3,]   24     0
[4,]   12     1
[5,]   NA    NA
[6,]   17     1


<h3>Arreglos</h3>

Un arreglo es una matriz de n-dimensiones que se define con la funcion `array()` que recibe los parametros de los datos y las dimensiones en las que se ordenan estos.

In [ ]:
#Definimos el array
ar<-array(data=1:24,dim=c(3,4,2))
print(ar)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



Para acceder a algun valor de este array solo debemos tener en cuenta el orden de acceso, primero fila, luego columna y por ultimo el bloque

In [ ]:
ar[2,3,1]

[1] 8

<h3>Marcos de datos</h3>

Marco de datos o data frame es el mas usado ya que permite almacenar o agrupar vectores con informacion de diferente tipo. La funcion para crearlo es `data.frame()` a la cual se le agregan los vectores.

In [ ]:
num<-c(13,25,16,17,18)
letras<-c("A","B","C","D","E")
logica<-c(TRUE,FALSE,TRUE,FALSE,TRUE)

marco<-data.frame(num,letras,logica)
print(marco)

  num letras logica
1  13      A   TRUE
2  25      B  FALSE
3  16      C   TRUE
4  17      D  FALSE
5  18      E   TRUE


Ahora bien solo requerimos la columna letras de nuestro data frame, para ello realizamos lo siguiente:

In [ ]:
print(marco["letras"])
marco[["letras"]]
marco$letras

  letras
1      A
2      B
3      C
4      D
5      E


[1] "A" "B" "C" "D" "E"

[1] "A" "B" "C" "D" "E"

Como podemos ver las 3 opciones son validas pero la primera nos la muestra estructurada como marco y las otras nos la muestran en forma de vector.

<h3>Listas</h3>

Son conjunto de datos que puede contener otros tipos de objetos como los mencionados anteriormente para ello se usa la funcion `list()` el cual recibe como parametros los objetos separados por comas.

In [ ]:
a<-c("Perro","Gato","Conejo")
b<-matrix(1:12,ncol = 3,nrow=4)
c<-marco
lista<-list(a,b,c)
print(lista)

[[1]]
[1] "Perro"  "Gato"   "Conejo"

[[2]]
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

[[3]]
  num letras logica
1  13      A   TRUE
2  25      B  FALSE
3  16      C   TRUE
4  17      D  FALSE
5  18      E   TRUE

